name: Monitoring Streams Deployment
on:
  workflow_dispatch:
  # push:
  #   branches: [ "master" ]
  #   paths:
  #   - 'MonitoringData.Infrastructure/**'
  #   - 'MonitoringData.DataLoggingService/**'
  #   - '.github/workflows/monitor-logger-deploy.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{secrets.Docker_Username}}
        password: ${{secrets.Docker_Password}}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./MonitoringData.DataLoggingService/Dockerfile
          push: true
          tags: ${{ secrets.Docker_Username}}/monitoringdatadataloggingservice:dev
  # deploy:
  #   needs: build
  #   runs-on:
  #    group: setihost-group
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: microk8s.kubectl rollout restart deployment e2stream
  #     - run: microk8s.kubectl rollout restart deployment gbstream
  #     - run: microk8s.kubectl rollout restart deployment nhstream
  #     - run: microk8s.kubectl rollout restart deployment e1stream
  #     - run: microk8s.kubectl rollout restart deployment e1thstream
  #     - run: microk8s.kubectl rollout restart deployment e2thstream
      
